#!/bin/sh

# Set up bugzilla and run apache2
cd /var/www/html

# Remove voting disable file
rm -f extensions/Voting/disabled

# Verify bugzilla setup
./checksetup.pl

# Change ownership
chown -R www-data:www-data .

# Remove stall pid file
rm -f /var/run/apache2/apache2.pid

# Start apache2
. /etc/apache2/envvars
/usr/sbin/apache2 -D FOREGROUND
